### ISSUE TITLE
Adding collection to itself

### ISSUE THREAD

**Issue by carlotxra** [rwobben/banking#1]
https://github.com/rwobben/banking/blob/cd7332d69474339e1db2b0c3e2e1e5174b832d88/Banking/Customer.class.st#L12

Hi

Probably related to your message on the pharo mailing/discord channel.

Looks like there is a spelling mistake and you are adding the collection to itself i.e. bankaccounts instead of bankaccount.

**Comment by rwobben** [comment]
yep, thanks that was the culprit.
